### PR TITLE
Update index.js

### PR DESCRIPTION
**Pull request by trevster344**
Vue 3.0 support. If there is anything missing to make this happen please let me know. I made the changes locally and tested with no issues in my 3.0 apps.

### CODE REVIEW

**Comment by wuori** [comment]
No, I didn't have internet the last two days (moving) so I'll check this out. Thanks!

**Comment by wuori** [comment]
Did you do any tests for backward compatibility with Vue 2? I plan to do it myself just wanted to check before. Thanks again

**Comment by trevster344** [comment]
> Did you do any tests for backward compatibility with Vue 2? I plan to do it myself just wanted to check before. Thanks again

I started off writing for both but I quickly realized it would need a little more work. The biggest difference is the hook names. `bind` is now `beforeMount` in vue 3 when writing directives. Additionally `vnode.context` is now accessed with `binding.instance` and vue.prototype is now vue.config.globalProperties.

**Comment by wuori** [comment]
@trevster344 Sounds good. Let me double-check some things and see if I need to augment the documentation. I myself haven't used Vue 3 much so I'm a little lost. If nothing else I'll tag the current as "Vue 2 Support" or something then merge your PR into master to continue.

**Comment by trevster344** [comment]
> @trevster344 Sounds good. Let me double-check some things and see if I need to augment the documentation. I myself haven't used Vue 3 much so I'm a little lost. If nothing else I'll tag the current as "Vue 2 Support" or something then merge your PR into master to continue.

**Comment by trevster344** [comment]
Accidental close.

**Comment by wuori** [comment]
I'm about to merge this, bump up to version `1.0.0` for Vue 3, and keep `0.x.x` for Vue 2. Thank you so much for your help on this, sorry it took so long!

**Comment by trevster344** [comment]
@wuori  No problem! Thank you.

**Pull request merged**
